### ISSUE TITLE
[Feature] Admin Only Links

### ISSUE THREAD

**Issue by Defying00** [Ctrlpanel-gg/panel#1004]
### Feature Description

Just a check box on the important links configuration to allow only admins and moderators to see the link.  This allows you to add links for your admins for things like support guides and internal management tools.

### Solution Idea

Just a simple check box that when checked allows only moderators and administrators (or any staff role at all) to see the important link

**Comment by lezetho** [comment]
You could just write yourself a addon for this.

**Comment by S0ly** [comment]
we dont really understand what you mean, could you elaborate ? @Defying00

**Comment by Defying00** [comment]
In the "useful links" section where you can make links for users that appear at the top of the page.  When you create one of these just allowing only admins to see it.

I did however go ahead and make a version of this, so its not critical now.

**Comment by S0ly** [comment]
yep its currently not planned and very sepecific to your use, you may want to make an add-on for that, or just an internal documentation :)

still thanks for the suggestion !
