### ISSUE TITLE
[Bug]: Checking the status of mail settings in the db

### ISSUE THREAD

**Issue by drylian** [Ctrlpanel-gg/panel#1007]
### What is your request about?

Shouldn't Settings be "SETTINGS::" instead of "SETTINGS:"?

![image](https://github.com/user-attachments/assets/abe0e743-3144-45b3-ad1c-021a1e4d0b12)

Filepath:app/Providers/AppServiceProvider.php

### Branch

main

### Ctrlpanel Logs

```Shell
not have logs
```

**Comment by Zastinian** [comment]
This does not apply to the new version, you are checking the stable branch and not the development branch.

**Comment by 1day2die** [comment]
thanks!
