### ISSUE TITLE
[Bug]: Role on Purchase flag doesn't works

### ISSUE THREAD

**Issue by MrWeez** [Ctrlpanel-gg/panel#1011]
### What is your request about?

Checkbox **Role on Purchase** in Discord settings does't save on submit click. You literally can't setup this feature because of this

### Branch

development

### Additional Info

[Screencast from 2024-11-09 23-22-30.webm](https://github.com/user-attachments/assets/ae0388f2-a180-4038-ad93-05b67de2e723)

**Comment by 1day2die** [comment]
fixed
