### ISSUE TITLE
[Bug]: ClientID must be set on discord linking

### ISSUE THREAD

**Issue by 1day2die** [Ctrlpanel-gg/panel#1013]
### What is your request about?

![grafik](https://github.com/user-attachments/assets/d8833e30-ae4b-4970-a1e9-34ecfcc4586d)

### Branch

main

**Comment by 1day2die** [comment]
this is due to this code in /config/services.php
![grafik](https://github.com/user-attachments/assets/1d701626-a67f-4a1e-92e4-d1e227d962e6)


sadly trying to fix it using the settings like this

**Comment by AGuyNamedJens** [comment]
DiscordSettings won't work in config files through the database, it's because Laravel uses it's config files before services like the Settings package loads. Keep them in the environment or make them fixed / overwrite them somewhere after everything was initialized.. i had this bug before

**Comment by 1day2die** [comment]
fixed

**Comment by 1day2die** [comment]
https://github.com/Ctrlpanel-gg/panel/pull/1014
