### ISSUE TITLE
[Feature] Discount on a product

### ISSUE THREAD

**Issue by luckyloo1730** [Ctrlpanel-gg/panel#1045]
### Feature Description

Make it so that admins can setup products discounts, and when a user orders a product they get charged less for the whole month. And like for the next month they get charged the normal rate, make it so you can config it, does the discount work on renewal or only on new purchases

### Solution Idea

You could add a page in the admin panel like that, and when it's a discount on products, just make a strike through on the old price and then add the new price beside it, change the rate for the month to the user. It should be implemented since it would be a really useful feature because it'll be much more easier to offer discounts and special prices.

**Comment by S0ly** [comment]
coupon apply price reduction on product, wen your buying a product you just have to enter to coupon code and you will get % or credit reduction, but it actually work on all products

**Comment by loulou133** [comment]
> coupon apply price reduction on product, wen your buying a product you just have to enter to coupon code and you will get % or credit reduction, but it actually work on all products

I don't think there's a place in server creation where you can put a discount code like on the page for buying credits.

**Comment by S0ly** [comment]
no you have coupon codes, that are codes that you can put wen buying any type of server they basicly do the same thing, they just apply to all type of product

**Comment by S0ly** [comment]
but they dont display a reduction, and they also dont apply to only one product

**Comment by loulou133** [comment]
> no you have coupon codes, that are codes that you can put wen buying any type of server they basicly do the same thing, they just apply to all type of product

So, can we use coupons to get a discount on the price of a server we want to create, instead of getting a discount on the purchase of credits?

**Comment by S0ly** [comment]
yes coupons apply to servers, but I dont known if they apply to purchase of credits I dont think so

**Comment by S0ly** [comment]
wait no

**Comment by loulou133** [comment]
> wait no

When I look at the demo, they just talk about discounts in the store and not when creating servers.

**Comment by S0ly** [comment]
yeah it made me bug, I think your right coupons only work on the store that only contains server slots and credits

**Comment by loulou133** [comment]
> yeah it made me bug, I think your right coupons only work on the store that only contains server slots and credits

It's sad that they're not putting this on the panel at the moment :(

**Comment by S0ly** [comment]
I guess that I will put that as a feature for incoming version, you can always add it yourself into the panel since its open source, or make an add-on that you can sell
