### ISSUE TITLE
[Bug]: User Search Returns No Results and Triggers SQL Error

### ISSUE THREAD

**Issue by Maximilian1021** [Ctrlpanel-gg/panel#1047]
### What is your request about?

Description:
When using the user search feature, an animation is displayed indicating that the search is in progress. However, no results are returned, and errors are generated in the background. This seems to be related to a missing column in the database query.

Steps to Reproduce:

    Open the user search interface.
    Enter any search term.
    Observe the behavior: The animation starts, but no results are returned.

Expected Behavior:
The search should return matching users from the database, if they exist.

Actual Behavior:
The search returns no results, and the following error is logged:

Error Message (Excerpt):

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'discordUser.id' in 'WHERE'

Summarized Logs:
[2024-11-21 15:42:53] production.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column
'discordUser.id' in 'WHERE' (Connection: mysql, SQL: select count(*) as aggregate from users
left join model_has_roles on users.id = model_has_roles.model_id left join roles on
model_has_roles.role_id = roles.id where model_has_roles.model_type = App\Models\User
and (LOWER(discordUser.id) LIKE %...%

Additional Notes:
It appears that the column discordUser.id does not exist or is not correctly defined in the database but is referenced in the query.

Log Details:
A full log excerpt is available at the following link:
[Link to the Logs]

Thank you in advance for addressing this issue! Please let me know if additional information is required.

### Branch

main

### Solution idea

I am not familiar with programming. That's why I'm not going to suggest a solution here.

The idea I would have is to adapt the MySQL search criteria to the database structure!

### Ctrlpanel Logs

```Shell
https://ptero.co/cameqokoge
```

**Comment by 1day2die** [comment]
https://github.com/Ctrlpanel-gg/panel/pull/1050
