### ISSUE TITLE
[Bug]: Free Products Are Suspended Despite Having No Costs

### ISSUE THREAD

**Issue by Maximilian1021** [Ctrlpanel-gg/panel#1048]
### What is your request about?

**Description**:
Products configured as free and requiring no balance are being suspended when the user’s account balance is 0 Coins. This occurs even though the products are correctly set up as free (see attached screenshots). However, if the user has a small balance (e.g., 0.005 Coins), the products are not suspended, and previously suspended products are automatically reactivated by the system.

**Steps to Reproduce:**

    Configure a product as free, requiring no account balance.
    Create a user account with a balance of 0 Coins.
    Observe that the server is automatically suspended after a while, despite the product having no costs.
    Add a minimal amount of Coins (e.g., 0.005 Coins) to the user’s account.
    Observe that suspended products are reactivated and no further suspensions occur.

**Expected Behavior:**
Free products should not be suspended regardless of the user’s account balance, as they incur no costs.

**Actual Behavior:**

    Products are suspended when the user’s balance is 0 Coins after some time.
    With a balance of 0.005 Coins or higher, products remain active, and previously suspended products are reactivated.

**Screenshots**

![Server Overview](https://github.com/user-attachments/assets/aac6bf5b-58ea-4a2e-aa9e-9de7cea38043)
![Log](https://github.com/user-attachments/assets/8ebd4f47-71d0-475b-ac0f-eb1468a8866d)
![Produkt](https://github.com/user-attachments/assets/35d9f532-936c-4b49-a6de-80bf645f2b74)

### Branch

development

### Solution idea

I am not familiar with programming. That's why I'm not going to suggest a solution here.
The problem seems to be related to the validation of the credit amount in the system, even if the product is explicitly configured as free.

### Ctrlpanel Logs

```Shell
Nothing visible in the logs
```

**Comment by 1day2die** [comment]
https://github.com/Ctrlpanel-gg/panel/pull/1043

**Comment by 1day2die** [comment]
the fix needs testing by someone

**Comment by Maximilian1021** [comment]
![grafik](https://github.com/user-attachments/assets/2aafb1bd-6aa6-4bce-af9a-c5227337d030)
![grafik](https://github.com/user-attachments/assets/b15a557a-b6d9-4234-8c99-61dec7eae150)
Same after patch

**Comment by S0ly** [comment]
not fixed

**Comment by IceToast** [comment]
> ![grafik](https://private-user-images.githubusercontent.com/13157092/388655012-2aafb1bd-6aa6-4bce-af9a-c5227337d030.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMzEyNzIsIm5iZiI6MTczMjIzMDk3MiwicGF0aCI6Ii8xMzE1NzA5Mi8zODg2NTUwMTItMmFhZmIxYmQtNmFhNi00YmNlLWFmOWEtYzUyMjczMzdkMDMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDIzMTYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNjA0Zjg3OGJjMzQ1YzYzOTViZDM2NTU4NGM5YTY2NDMzMmY5NzJiNzlmZGRiOWU5ODZhOGEzYTBhMDNlMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.InC_o6AEAr0vDaGm0cMpqP0lNjVVmJaUT_wEEEi-3XA) ![grafik](https://private-user-images.githubusercontent.com/13157092/388655021-b15a557a-b6d9-4234-8c99-61dec7eae150.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMzEyNzIsIm5iZiI6MTczMjIzMDk3MiwicGF0aCI6Ii8xMzE1NzA5Mi8zODg2NTUwMjEtYjE1YTU1N2EtYjZkOS00MjM0LThjOTktNjFkZWM3ZWFlMTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDIzMTYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0NDU1MjdkMGZmOThiNjJjYTNjYmMyZTQ4M2IwYjQwNDBkMWFlZTRlODBmZWNiNjI0NDBkODdlYTU5NGRkMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TkpQa8hpFDnG2uzqdZENZtHK4YqqGUMim67ElpZWLuE) Same after patch

Did you reproduce the bug or did you want the fix applies to already suspended free servers too?

**Comment by Maximilian1021** [comment]
Mistake on my part. Someone has interfered!
