### ISSUE TITLE
When setting ReCAPTCHA in settings, it doesn't update in .env

### ISSUE THREAD

**Issue by AwesomeKalin** [Ctrlpanel-gg/panel#1054]
### What is your request about?

When I updated to v1, my ReCAPTCHA implementation broke. I tried changing keys and nothing. It's just showing as the test ReCAPTCHA.

### Branch

main

### Additional Info

Site key in login html is ?????? and is set to ?????? in the config 

(edited by soly)

**Comment by S0ly** [comment]
need someone to verify this :)

**Comment by MrWeez** [comment]
I'm not sure, but reCaptcha now use keys from .env and not from settings. Can you please check this?

**Comment by S0ly** [comment]
why from .env ? strange

**Comment by AwesomeKalin** [comment]
> did you just leaked your site key ?????

Site Key is public anyways. Secret key is what you keep private

> I'm not sure, but reCaptcha now use keys from .env and not from settings. Can you please check this?

Lemme see

**Comment by AwesomeKalin** [comment]
That'll be it, it's in the .env! Although, should be considered as a bug that updating it in the settings doesn't update it in .env, so I'll update the title of the issue

**Comment by S0ly** [comment]
thanks for the report

**Comment by 1day2die** [comment]
![grafik](https://github.com/user-attachments/assets/0bc20874-b64b-46f2-8c8f-231e323b1ce8)


that it very much correct. I dont quite know why since i remember in v09 we had it in settings too?
I will make it load from the settings just like i made it with discord. thanks for the report

**Comment by 1day2die** [comment]
Fixed in next update
