### ISSUE TITLE
Buggy layout

### ISSUE THREAD

**Issue by Zarroc05** [Ctrlpanel-gg/panel#1058]
### What is your request about?

The layout under /admin/users is a little buggy. The titles and contents have slipped one too far to the left. Under Pterodactyl_id is my avatar, under avatar my name and under name my role etc.

![Screenshot 2024-11-26 170803](https://github.com/user-attachments/assets/4e9cf0a8-7c7f-4d41-b058-5cb0a51b0de6)

### Branch

main

### Solution idea

Move content one further to the right.

### CtrlPanel Logs

```Shell
I don't have any current logs.
```

**Comment by S0ly** [comment]
![image](https://github.com/user-attachments/assets/2f5e6ff8-868c-472b-a597-cd7ff6ffd72d)
I dont have any issue whit it 
can you give me your screen size ?

**Comment by S0ly** [comment]
never mind i'm dumb

**Comment by 1day2die** [comment]
fixed in next update
