### ISSUE TITLE
Server creation is returning 'no available nodes' even when the first node is free but not permitted for the specified product.

### ISSUE THREAD

**Issue by BolverBlitz** [Ctrlpanel-gg/panel#1059]
### What is your request about?

You have 2 nodes on the same location, but only node 2 is avaible for the product you wanna buy then you do not get any node.

on getAvaibleNode the arguments passed are location and product, the collection var that should hold only nodes the product is allowed on gets filled by a SQL query with only the where condition of location_id. 
The first avaible node gets returned by the function, so if the first node is avaible but the product is not allowed it would show that there are no avaible nodes.

### Branch

main

### Solution idea

I think a query like this should fix the issue
```
SELECT nodes.*
FROM nodes
JOIN node_product ON nodes.id = node_product.node_id
WHERE nodes.location_id = :location_id
  AND node_product.product_id = :product_id
ORDER BY nodes.id
```
If there isn´t any PHP magic already doing it, also limit the SELECT on id as thats the only value you use.
Also overwriting a function parameter, talking about checkNodeResources, is usualy considered poor coding practice, on that note when only the node->id is used anyway, why pass the entire node object?

**Comment by 1day2die** [comment]
fixed. thanks
