### ISSUE TITLE
Incorrect display conditions for the "Buy more Credits" button

### ISSUE THREAD

**Issue by MrWeez** [Ctrlpanel-gg/panel#1062]
### What is your request about?

Button is displayed only if the user hasn't enough credits relative to the price, but not the minimum number of credits for the product

https://github.com/Ctrlpanel-gg/panel/blob/43cac5bd99019e1548907b5222f6e0d8c7dae039/themes/default/views/servers/create.blade.php#L254-L260

### Branch

main

### Solution idea

Whoever allowed this to happen will fix it (Weez will fix his mistake)

**Comment by 1day2die** [comment]
fixed in new update
