### ISSUE TITLE
"Minimum Credits" parameter is not taken into account when creating a new server

### ISSUE THREAD

**Issue by MrWeez** [Ctrlpanel-gg/panel#1063]
### What is your request about?

Conditions:
User Credits - 1000
Product price - 1500/mo
Minimum Credits - 10

When trying to create a new server, the user sees a button with the text "Not enough Credits!", although under our conditions the user can allow the server, which should work for about 22 days

### Branch

main

### Solution idea

That doesn't seem to be how it should work... This should remain on the backend side, but it was displayed in the frontend and therefore does not work properly

![image](https://github.com/user-attachments/assets/634c822f-c04d-4365-ae68-5f1e02638c5b)

**Comment by 1day2die** [comment]
fixed in next update
