### ISSUE TITLE
A message about the lack of available nodes when creating the server before selecting the egg

### ISSUE THREAD

**Issue by MrWeez** [Ctrlpanel-gg/panel#1064]
### What is your request about?

When creating a server after selecting a nest, you see a message that there are no nodes to create the server, which disappears after selecting an egg. A simpler explanation is on the video, it is attached below

[Screencast from 2024-11-28 04-27-05.webm](https://github.com/user-attachments/assets/693f1156-5f1f-40dd-91e1-53ce3c0b8338)

### Branch

main

### Solution idea

Fix this in the next version

**Comment by 1day2die** [comment]
fixed in next update
