### ISSUE TITLE
Default error page on ticket rate limit

### ISSUE THREAD

**Issue by MrWeez** [Ctrlpanel-gg/panel#1067]
### What is your request about?

Tickets have a delay in creating and sending messages, but it returns a standard Laravel error page instead of a small notification
Also, if you create a ticket, and let's say the message length is less than 5 characters, then you get the error that the minimum length is 5 characters, and at the same time the rate limit rules apply to you and you cannot create a ticket again before rate limit end

### Branch

main

**Comment by 1day2die** [comment]
fixed in latest update
