### ISSUE TITLE
Blank page on login/register

### ISSUE THREAD

**Issue by MrWeez** [Ctrlpanel-gg/panel#1076]
### What is your request about?

If you click "Sign in" on the login page without entering data, you will get a blank page instead of a redirect with an error message. The same applies to registration, if you enter the data, but the passwords do not match, you will get a blank page instead of an error message.

Video:
[Screencast from 2024-12-18 18-32-04.webm](https://github.com/user-attachments/assets/d54c7377-958d-4599-a822-bff37fc81f6c)

### Branch

development

**Comment by 1day2die** [comment]
fixed
