### ISSUE TITLE
Prouduct Vouchers

### ISSUE THREAD

**Issue by William0216** [Ctrlpanel-gg/panel#130]
# 🚀 Feature Request

It would be incredible and powerful for us to be able to provide product vouchers. 
For example, we would love this so that we could set up a better free server system where our users can redeem one free server each (currently we use the ptero API however the server doesn't appear on the Control Panel). 
Another application would be giving away x amount of servers lasting y time to the winners of a giveaway or promotion.

I would propose such a feature have the following options:
-Product Choice
-Code Expiration Time (allowing never)
-Max # of users allowed to claim
-Uses per person
-Product Duration (Time until server suspension/deletion/charging credits begins + option for which of those you want applied)

**Comment by anondev-sudo** [comment]
Good idea

**Comment by Bazimek** [comment]
Very good idea

**Comment by S0ly** [comment]
except if im going crazy, I think I seen this already implemented in the main branch

**Comment by GeckoBoy84** [comment]
Not implemented.
