### ISSUE TITLE
[feature] Read before continuing alert

### ISSUE THREAD

**Issue by 144reasons** [Ctrlpanel-gg/panel#136]
# 🚀 Feature Request

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

A cool thing that could be added is a kind of "Read me before continuing" alert to the dashboard, and maybe even an endpoint to the api that could create these. This could be useful to create alerts for specific users who, for example, left the discord of the host and need to stay in it, but the bot cant dm them letting them know this because they have their dms closed.

**Comment by anondev-sudo** [comment]
This is good idea that admins can sent notifications to users on dashboard or using api. There should be also that you can choose if you want to send just notification on dashboard or just email notification or both.

**Comment by somerandomcloud** [comment]
I agree with this, didnt think about email notifications

**Comment by AVMG20** [comment]
A little box can be added in the register page. But users will often ignore this. I think you are mainly looking for a way to use the api to send notifications. Right now this is not implemented yet and already requested. But in the meantime: You could for example use the controlpnale api to fetch the leaving user's email. And send an email using you bot :)

**Comment by somerandomcloud** [comment]
Lovely Idea, love it!

**Comment by S0ly** [comment]
I dont understand the request is it still needed ?

**Comment by sybetjeh** [comment]
Hire a developer to get features specific for your needs. Ctrlpanel.gg is a foundation to build on
