### ISSUE TITLE
Api endpoint for getting purchases

### ISSUE THREAD

**Issue by anondev-sudo** [Ctrlpanel-gg/panel#166]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

(Write your answer here.)

> How it is possible to to know if user has purchased credits using api?
I am making system that when user left server and had account, email will be sent that it was deleted and account will be deleted using api.
But I don't want to do this for users who have purchased credits from store (not just using free initial credits). For those I will send them different email manually, I will just make that bot will send message to private channel letting me know that user who purchased credits has left.

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

(Describe your proposed solution here.)

Make api endpoint to get all purchases and purchases of specific user.

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

(Write your answer here.)

**Comment by IceToast** [comment]
You could check if a user is "client". An user is only a client when he made a successful payment.

**Comment by anondev-sudo** [comment]
Yes but I want to get list of purchases, to know how many credits has the user purchased

**Comment by 1day2die** [comment]
you can include payments with the route

/api/users?include=payments
