### ISSUE TITLE
Show available plans

### ISSUE THREAD

**Issue by anondev-sudo** [Ctrlpanel-gg/panel#232]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

Users who don't have required credits to make server, can't browse the plans.

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

Change the plans design, when you click on the create server, show plans in cards and then there should be button "Use this plan" or "Purchase", when you click on it, show selector to choose egg, node and name + description fields.

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

Alternative:

Instead of the 'you do not have the required amount of Credits to create a new server!', remove it so users can see the server options, but if they try to make server without enough credits, show the message

**Comment by 1day2die** [comment]
Just lower your "Minimum Credit to create a server" config?
