### ISSUE TITLE
Reverse Proxy API integration

### ISSUE THREAD

**Issue by Hiekki4** [Ctrlpanel-gg/panel#233]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

No

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

Make like a integration with the reverseproxy api https://github.com/j122j/reverseproxy 

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

No

**Comment by anondev-sudo** [comment]
Any updates on this?
I think that it should be part of the billing portal, as when the user has deleted server on cp.gg with linked domain, it should auto delete the proxy and cert (make DELETE request to reverse proxy api). When you do this that users can link domains using discord bot, you don't know when server was deleted so you can delete proxy.

Users should have option in 3 dot menu for server to manage domains when it's enabled.
Popup should be displayed then, there should be option that you can set how many custom domains can be linked to one server (per product). Users should have option to link domains to specific allocations (if there is more allocations) and to unlink domains. When they delete server, all custom domains should be auto unlinked.
