### ISSUE TITLE
Login to pterodactyl with Controlpanel.gg

### ISSUE THREAD

**Issue by anondev-sudo** [Ctrlpanel-gg/panel#245]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

You can't add Discord oauth to controlpanel.gg.

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

Create oauth server on controlpanel.gg, make plugin for pterodactyl that replaces login form with button "Login with dashboard", when you click on it, redirect user to controlpanel.gg oauth link where users click on Authorize and it will redirect them back to pterodactyl.

Then make support for Discord oauth login and register on controlpanel. Add optional option to completely disable registration and login form on controlpanel and replace it just with Discord auth.

In the feature, more oauth providers support can be added.

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

(Write your answer here.)

**Comment by IceToast** [comment]
As you described that will require a custom plugin for pterodactyl which is not in scope yet. This FR will be blocked (not closed) until someone decides otherwise :)

**Comment by S0ly** [comment]
I don't get why not planned

**Comment by S0ly** [comment]
this would be a really cool addition to the panel even as an option

**Comment by S0ly** [comment]
by reading myself I confuse myself
