### ISSUE TITLE
Send suspended server notification just once

### ISSUE THREAD

**Issue by anondev-sudo** [Ctrlpanel-gg/panel#246]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

User has received notification (both email and database) 3 times that their servers were suspended
### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

Make that user will receive the notification just one time when their server(s) were suspended.

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

Alternative:
Include atleast server name it the notification to not make users confused why they received that more times.

**Comment by GeckoBoy84** [comment]
Not possible with the new billing cycles
