### ISSUE TITLE
[feature] Coupon Codes

### ISSUE THREAD

**Issue by GeckoBoy84** [Ctrlpanel-gg/panel#253]
# 🚀 Feature Request

### Is your proposal related to a problem?

Users can get credits with a voucher, however they are unable to get a % off when they purchase credits with IRL currency.

### Describe the solution you'd like

In the voucher page you can select if it is a voucher for xyz credits or if you want it to be a coupon code with xyz% off purchase.

**Comment by 1day2die** [comment]
i like the idea. ill look into this

**Comment by partridge420x** [comment]
I dont mean to revive a dead post, but this would be ideal, especially if your trying to do partnerships

**Comment by S0ly** [comment]
@Ferks-FK its listed as in progress for you, any news or PR ?

**Comment by S0ly** [comment]
why nobody respond to me :(

**Comment by MrWeez** [comment]
Implemented in #857
