### ISSUE TITLE
[feature] Gopay gateway

### ISSUE THREAD

**Issue by FilexCZE** [Ctrlpanel-gg/panel#256]
# 🚀 Feature Request

### Is your proposal related to a problem?

No.

### Describe the solution you'd like

Add a new GoPay payment gateway.

Document: https://doc.gopay.com/

### Additional context

GoPay adds the option of payment by credit card for people who do not have paypal.

(If dev want pay for this feature, please contact me on discord: SinFileX#7759)

**Comment by anondev-sudo** [comment]
Good idea, gopay can be used also for paysafecard and others if I am not wrong.

**Comment by matyasvane** [comment]
Yes, this support:

Cards, Applepay, Googlepay, Paypal,  Bitcoin, Paysafecard, PremiumSMS, m-payment etc :)

CZ page: https://www.gopay.com/cs/platebni-metody/

**Comment by GeckoBoy84** [comment]
We will not be adding payment gateways only used in Indonesia to the main repo over other more important features

**Comment by matyasvane** [comment]
Indonesia? See intro doc, that gateway working in Europe.

**Comment by Mr-Rene** [comment]
This payment gateway works through Europe and not through Indonesia, and if I may say so, Vysoký Vagon itself uses it, so I see no reason why it shouldn't be added.

**Comment by Mr-Rene** [comment]
I also agree with the others that she should definitely join.

**Comment by 1day2die** [comment]
https://market.ctrlpanel.gg/product/gopay-payment-gateway/
