### ISSUE TITLE
Change getting started message

### ISSUE THREAD

**Issue by anondev-sudo** [Ctrlpanel-gg/panel#26]
# 🚀 Feature Request

### Is your proposal related to a problem?
I can't change getting started notification without code modification 

### Describe the solution you'd like

Add that you can change getting started message by rewriting database using phpmyadmin

### Additional context

*Is there anything else you can add about the proposal?

**Comment by anondev-sudo** [comment]
This should be added to dashboard too like useful links were added https://github.com/ControlPanel-gg/dashboard/issues/25

**Comment by LogischJo** [comment]
I will take a look at it

**Comment by GeckoBoy84** [comment]
Already Implemented
