### ISSUE TITLE
[feature] Paysafe card gateway

### ISSUE THREAD

**Issue by TheNickcrafter** [Ctrlpanel-gg/panel#261]
# 🚀 Feature Request

### Is your proposal related to a problem?

Yes, not all users want to use PayPal. Paypal takes a larger cut of the payment too.

### Describe the solution you'd like

Add Paysafe as payment gateway
https://www.paysafecard.com/

**Comment by MCTzOCK** [comment]
It would be very useful to add an paysafecard integration. PayPal can only be used by people over 18 years of age. If you would support Paysafecard, other junger people could use the services too.
