### ISSUE TITLE
[feature] Search on servers page

### ISSUE THREAD

**Issue by anondev-sudo** [Ctrlpanel-gg/panel#263]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

You can't find your server on dashboard when you have many servers.

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

Add search field to dashboard servers page where you can search your servers in cards by their name, description, plans, ...

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

(Write your answer here.)

**Comment by GeckoBoy84** [comment]
Implemented at some point since this was opened
