### ISSUE TITLE
Automatically choose a Node for Installation

### ISSUE THREAD

**Issue by Tix-Hosting** [Ctrlpanel-gg/panel#286]
# 🚀 Feature Request

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

It is currently the case that in product linking it is possible to select the nodes on which the customer can install the server. Now, when creating the server, the customer can choose for himself which of the allowed nodes the server is to be installed.

I think it would be cool if there was an option that specifies that the panel automatically randomly selects a node on which the server is installed (taking into account whether there are still enough resources on the node for the server). The customer no longer has the confusion as to which node he should select and why, and it is also easier for administration, as the processes are automatically taken over by the system ... If there are no longer enough resources available on any of the permitted nodes, this can be output by an error message.

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

Product linking is kind of related to that :)

**Comment by AVMG20** [comment]
i like the idea, but how do you picutre us to add this? cuss some ppl might like it that the customer can select the node, since 1 node may be stronger or better than another node, and this could be reflected back to the customer in price (and later also in showing specs or something of the node)

**Comment by anondev-sudo** [comment]
Maybe some random node should be selected, but there should be option to change it using drop down

**Comment by Tix-Hosting** [comment]
@AVMG20 

I think what Anon Dev is a pretty good option! The panel automatically selects a node (as written in the Original Issue) and selects it automatically. Now the user can change this afterwards. Then in the options there is the option like: "LET_CUSTOMER_CHOOSE_NODE", this can be "True" or "False". If it is set to False, then the customer cannot change the automatic selection of the node because the option is grayed out and cannot be clicked ... :)

So both use cases are covered, those who want to let their users choose the node and also the others who do not want the customers to be able to choose a node :)

**Comment by Zoe8338** [comment]
> I like the idea, but how do you picture us to add this? cuss some ppl might like it that the customer can select the node, since one node may be stronger or better than another node, and this could be shown to the customer in price (and later also in showing specs or something of the node)

A switch which you can turn to choose node / location. If the switch is turned to "nodes" the costumer can choose which node to deploy in, if it's to location the costumer will only see the locations and the panel will decide the node to deploy in. This could be set by plan instead of system wide.

**Comment by anondev-sudo** [comment]
https://github.com/pterodactyl/panel/issues/3732
Don't forget that pterodactyl api will allow you to overallocate node, make sure to fetch node usage and check if it won't go over the set limits before creating server.

**Comment by wynn-dev** [comment]
I think this should be prioritised. Having 20 or more nodes to choose from is a pain for both the client and the manager. Plus ppl creates servers on one node all the time, so I need to monitor usage on a daily basis.
I believe many people should feel my pain 🤣

**Comment by AGuyNamedJens** [comment]
I'm currently creating an addon that allows you to select the server's location (not node itself, the group of nodes pterodactyl calls a location) which will assign your server on the first possible node. Technically it could tackle this issue to resolved in the future

**Comment by anondev-sudo** [comment]
You could PR it to this repo then to solve this issue

**Comment by 1day2die** [comment]
yeah, but sadly many people think like this

![image](https://user-images.githubusercontent.com/8725848/179905394-0e1e13b1-4e57-4fdf-80cd-c2ddf745f648.png)

**Comment by AGuyNamedJens** [comment]
The addon exists for the current version, will most likely be added into the core later, aiming at the new version for that

**Comment by AGuyNamedJens** [comment]
Will be in 0.9.9

**Comment by S0ly** [comment]
Closed by PR #950
