### ISSUE TITLE
[feature] Taxes per User

### ISSUE THREAD

**Issue by Zoe8338** [Ctrlpanel-gg/panel#368]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

I guess if you want to make a legal business out of this panel then yeah.

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

The panel needs a TAX system. When people sign up they'd have to fill a form with first and last name, email and local of residence and maybe a mobile phone as well. Then with thi information (such as country) the panel would set a tax for that country, such as an example, Portugal is 23% tax.

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

People could make mandatory or not certain fields of the form such as street and phone number or something.

**Comment by 1day2die** [comment]
isnt tax calculated on the country the company resides?

**Comment by Zoe8338** [comment]
> isnt tax calculated on the country the company resides?

No, TAX is payed in percentage by where the costumer resides. Thats the reason they all ask you for your country of residence and give you a tax on that.

**Comment by Zoe8338** [comment]
> Thats only true when you collect the data from where you receive money and taxes. If you do not differentiate it doesnt matter. Depends on the country and tax laws at your location tho.

It'd be better if you make an option to turn that on and off then maybe.
