### ISSUE TITLE
Remove Salutation and Closing from email notification

### ISSUE THREAD

**Issue by ok236449** [Ctrlpanel-gg/panel#387]
When you send a notification on the dashboard, you may face the issue of doubling these.

Let's say, you want to notify a user by both email and dashboard notifications. You create a notification something like this:
![1](https://user-images.githubusercontent.com/89067167/152681000-262ec99d-ac20-4899-83ff-4ac6db642c33.png)
On dashboard, the notification would be sent normally, just like you wrote it.
![2](https://user-images.githubusercontent.com/89067167/152681055-fa186c89-7f40-4815-892e-78f7bfea18b1.png)
The mail would have 2 salutations and 2 closings.
![3](https://user-images.githubusercontent.com/89067167/152681091-6035ce52-a581-4380-b118-0a418a66cfa3.png)

**Expected behavior**
The automatic salutation and closing should be removed from these notification emails, but kept on the other mails(reset password, ...)

Adding the salutation to dashboard notifications would work, but that is not the best way of fixing this. Removing the salutation from mail is a way better idea as it allows for customizability and if you were to notify someone, you would definitely write them on your own.

**Comment by S0ly** [comment]
have this been fixed since ?

**Comment by GeckoBoy84** [comment]
No

**Comment by MrWeez** [comment]
Am I missing something? I see in the message only the text that you wrote. Or do you mean to completely remove the greeting and ending from the email template for notifications?

**Comment by S0ly** [comment]
idk if you can test if the issues is still here so we can ethier fix or close this issue it could be great @MrWeez ! :)

**Comment by MrWeez** [comment]
> idk if you can test if the issues is still here so we can ethier fix or close this issue it could be great @MrWeez ! :)

Although, I have an idea. We can add a greeting to the notification template in the dashboard.

**Comment by MrWeez** [comment]
Then we won't have to write a greeting in the notification text.

**Comment by S0ly** [comment]
I dont have working mail so I cannot check but the hello just need to be removed

**Comment by S0ly** [comment]
like it make no sense to use a template on a custom mail

**Comment by MrWeez** [comment]
> like it make no sense to use a template on a custom mail

Ok, I will try to solve this problem. I'll assign myself for now so I don't forget.

**Comment by S0ly** [comment]
it should be pretty easy to fix I just dont have time for it since it a medium priority and I cannot test it 
but yeah fixing it should be easy and nice to not have this problem
thanks weez :)

**Comment by MrWeez** [comment]
> it should be pretty easy to fix I just dont have time for it since it a medium priority and I cannot test it but yeah fixing it should be easy and nice to not have this problem thanks weez :)

If you want, I can give you an smtp account for testing xD

**Comment by S0ly** [comment]
no thanks weez xD

**Comment by MrWeez** [comment]
> no thanks weez xD

I couldn't get the job off on you 😂😂

**Comment by S0ly** [comment]
weez you dont feel I have enough pressure on me ? xD

**Comment by MrWeez** [comment]
> weez you dont feel I have enough pressure on me ? xD

I'm kidding. You already have a lot of tasks

**Comment by S0ly** [comment]
this is more complex than initially viewed and maybe needs refactoring of how the mails works
