### ISSUE TITLE
[feature] Make the welcomemessage customizable or atleast put in translationstrings

### ISSUE THREAD

**Issue by 1day2die** [Ctrlpanel-gg/panel#415]
# 🚀 Feature Request

### Is your proposal related to a problem?

yes/no

### Describe the solution you'd like

The welcome message is plain english without translationstrings. I would like it to be either
1. Fully editable or
2. in translation strings

**Comment by IceToast** [comment]
Fully customizable  welcome message (simple HTML Input which is already used in "Useful Links") with different versions for each language.

**Comment by GeckoBoy84** [comment]
Implemented
