### ISSUE TITLE
[feature] See Reffered by as a user and delete that

### ISSUE THREAD

**Issue by Tix-Hosting** [Ctrlpanel-gg/panel#460]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

No

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

It would be extremely useful if the user could see (even after registration (always)) which referrer ID he has used and, more importantly, which user this came from. A remove button should be placed next to it, with which the user can remove this ref link so that in future his purchases are no longer assigned to the referrer in commission mode. Since the user obviously cannot link a new Ref ID, a popup should warn them that the cancellation is irrevocable and whether they really want to do so.

This Information could possibly  be placed above the own ref link.

You could also point out to the user in the welcome email that he has used a ref token from the user "Username" with a link to remove this connection...

This feature protects users from unwanted ref scams that the user may not want...

**Comment by anondev-sudo** [comment]
Also there should be way to manually link referral code to existing user

**Comment by anondev-sudo** [comment]
Also I have made issue for it before and it was closed https://github.com/ControlPanel-gg/dashboard/issues/453

**Comment by Tix-Hosting** [comment]
> Also I have made issue for it before and it was closed https://github.com/ControlPanel-gg/dashboard/issues/453

Yeah i know :)

But this is a bit more Detailed and explains it a bit better as i provided an information how this could possibly be implemented and i guess your Issue were really going to address the admin side :)

**Comment by anondev-sudo** [comment]
I don't think that every host wants let users know eho referred them, maybe just show referral code if some was used, or make optional.

 In admin area, when you view some user, there should be which referral code did the user use on registration and who owns that code (also with link to that referral user), then there should be way to link/unlink specific referral code with the user. Also there should be way to edit/regenerate referral code of that user.

**Comment by Tix-Hosting** [comment]
Yes, of course you could make it optional, if the developers implement the feature, it's up to them :)

However, what is clear from my point of view is that those hostings that do not want to display this are slightly questionable, since this is simply information that a user should have access to, after all you can also hide ref links in, for example, short Links like Bit.Ly... Of course, the ref code is then displayed in the registration form, but since that is already filled in automatically, some will not know what this exactly means... And so users could get into certain fraudulent situations, because in many countries in europe it is required by law to state if it is a ref link. And when this issue is implemented, you give the user more control over their OWN account, which I think is extremely important, which I want to emphasize again here.

**Comment by Tix-Hosting** [comment]
> I don't think that every host wants let users know eho referred them, maybe just show referral code if some was used, or make optional.
> 
> In admin area, when you view some user, there should be which referral code did the user use on registration and who owns that code (also with link to that referral user), then there should be way to link/unlink specific referral code with the user. Also there should be way to edit/regenerate referral code of that user.


Yes, of course you could make it optional, if the developers implement the feature, it's up to them :)

However, what is clear from my point of view is that those hostings that do not want to display this are slightly questionable, since this is simply information that a user should have access to, after all you can also hide ref links in, for example, short Links like Bit.Ly... Of course, the ref code is then displayed in the registration form, but since that is already filled in automatically, some will not know what this exactly means... And so users could get into certain fraudulent situations, because in many countries in europe it is required by law to state if it is a ref link. And when this issue is implemented, you give the user more control over their OWN account, which I think is extremely important, which I want to emphasize again here.
