### ISSUE TITLE
[feature] Automatic Credit Package Selection

### ISSUE THREAD

**Issue by Tix-Hosting** [Ctrlpanel-gg/panel#470]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

**SITUATION AT IT IS RIGHT NOW:
If you have too few credits for a product, the button is currently grayed out and cannot be clicked... Therefore you cannot buy the Server without the Hassle to remember how many Credits you'll need and go to the store and purchase, or even calculate if you have some complicated Credit Packs**

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

**TARGET:
This should continue to be the case, but the button should still be clickable.  This should then be forwarded to the store.  However, not on the overview, but automatically on the next cheapest package, with the number of credits required to receive the package for one month.  After payment, the previously configured server will be automatically created with the previously selected configuration.**

Why one Month and not one Hour?

There were many Requests to add a system where you can buy a Custom Amount of Credits.. 

But this is not an good Idea for several reasons. One of it would be the Cost (Paypal, Stripe Fees etc.) for a 3 Credits Purchase...

But if you would lead to the Next low package to extend it too one hour, the feature wouldn't make any sense, as the User then has to do it every Hour and it would result in the same low Credits high Fees Purchase problem...

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

**PURPOSE:
After purchase, the server will be created automatically.  This greatly simplifies the ordering process, as the customer no longer has to switch back and forth between the tabs.  This also minimizes the transfer power required by the customer, which makes a purchase much more likely, as you facilitate the purchase process without the customer having to think about which package to buy...**

Please also add a Button somewhere in the Server Overview which let the User Buy the Package which is Required to Renew ALL Servers on his Account for a minimum Time of 30 Days, so that the Credits are enough for the timespan :)

**Comment by IceToast** [comment]
>This should continue to be the case, but the button should still be clickable. This should then be forwarded to the store. However, not on the overview, but automatically on the next cheapest package, with the number of credits required to receive the package for one month. After payment, the previously configured server will be automatically created with the previously selected configuration.

I dislike the idea of automatically choose a credit product for the user. That's opinionated.
- The user could want to just create a server for a day, what would be the cheapest package be? The smallest package available?
- The user could also want to create a server for a whole month (plans to do so), what would the cheapest package be then? Still the smallest package available? That would result in more clicks for the user as he has to navigate back to the store in order to choose a larger product.

However the idea to make the button redirect you to the store in general is a big plus.

**Comment by GeckoBoy84** [comment]
Replaced with #834
