### ISSUE TITLE
Error pages have default favicon not the one set

### ISSUE THREAD

**Issue by GeckoBoy84** [Ctrlpanel-gg/panel#681]
**Describe the bug 🐛**

Error pages have default favicon not the one set

**To Reproduce**
1. Go to any error page
2. Look at the favicon

**Expected behavior**
Favicon is the one set in the panel

**Comment by 1day2die** [comment]
Lol I thought the default laravel favicon bruh

**Comment by 1day2die** [comment]
https://github.com/Ctrlpanel-gg/panel/pull/1024
