### ISSUE TITLE
Mobile css admin/overview tables

### ISSUE THREAD

**Issue by GeckoBoy84** [Ctrlpanel-gg/panel#684]
**Describe the bug 🐛**

Mobile css admin/overview tables extend out of colour (unlike all other tables)

**To Reproduce**
1. Go to admin/overview on mobiles
2. See tables

**Expected behavior**
Either extend tables or shorten the text somehow so it all fits inside it's box

**Screenshots**

https://media.discordapp.net/attachments/1060642873969745971/1061212850762305606/image0.jpg
https://media.discordapp.net/attachments/1060642873969745971/1061212934090526750/image0.jpg

**Comment by IceToast** [comment]
Low Prio, because we generally don't really support mobile view.
