### ISSUE TITLE
[feature] Admin/Overview counters

### ISSUE THREAD

**Issue by GeckoBoy84** [Ctrlpanel-gg/panel#689]
# 🚀 Feature Request

### Is your proposal related to a problem?

Other than servers, all counters do not take into account of suspended users.

### Describe the solution you'd like

ADMIN OVERVIEW PAGE:
Total Users should become "unsuspended/total"
Total Credits should become "unsuspended user total/all non admin total"

### Additional context

A counter to calculate the credits for Unsuspended, non admin users (active tag)
And all non admin (total tag) what’s currently in 0.9
And a counter for the number of Unsuspended users including admins (active tag)
And all non admin (total tag) what's currently in 0.9

**Comment by 1day2die** [comment]
done
