### ISSUE TITLE
[feature] Ticket System Improvements

### ISSUE THREAD

**Issue by GeckoBoy84** [Ctrlpanel-gg/panel#709]
# 🚀 Feature Request

### Is your proposal related to a problem?

I do not want moderators to have access to all tickets, eg if they contain personal data.

(Write your answer here.)

### Describe the solution you'd like

The ability to set ticket categories with different permissions - moderator (and admin) or (just) admin with support for roles and permissions in 0.10

### Additional context

Would be great to also be able to change this on a per ticket basis in cases where it needs to be changed.

**Comment by 1day2die** [comment]
we are gonna consider this. but most likely not gonna add
