### ISSUE TITLE
[feature] Ticket System Message Editing

### ISSUE THREAD

**Issue by GeckoBoy84** [Ctrlpanel-gg/panel#710]
# 🚀 Feature Request

### Is your proposal related to a problem?

You have to edit the ticket message via language keys.

### Describe the solution you'd like

Add a settings option to the ticket settings allowing this message to be customised.

![image](https://user-images.githubusercontent.com/67899387/216792652-77056624-f35a-49f3-8f48-baad3e1d9d3a.png)

**Comment by 1day2die** [comment]
done
