### ISSUE TITLE
[Bug]: Ticket Email Notifications

### ISSUE THREAD

**Issue by GeckoBoy84** [Ctrlpanel-gg/panel#740]
### What is your request about?

The email notification for new replies to tickets seems to ignore the setting and DMs admins on a new reply.

### Branch

main

### Solution idea

Should follow same rules as creation.

### Additional Info

![image](https://user-images.githubusercontent.com/67899387/218567824-24de53f7-5152-4e34-b91b-aabadd6644d5.png)

**Comment by 1day2die** [comment]
fixed in latest dev build.

now uses the permission "admin.tickets.get_notification" to determine which users should be notified
