### ISSUE TITLE
[Feature] bitpave payment gateway

### ISSUE THREAD

**Issue by 1day2die** [Ctrlpanel-gg/panel#749]
### Feature Description

https://bitpave.com/

pay with crypto

### Solution Idea

1day2die will implement this

**Comment by S0ly** [comment]
have been this implemented since ?

**Comment by MrWeez** [comment]
> have been this implemented since ? 
> 

Yes, but 1d2d couldn't test it. At the moment, it is presented as an addon in the market.

**Comment by S0ly** [comment]
So what should we do ? 

I think it can be an addon since almost nobody use crypto it’s pretty rare

**Comment by 1day2die** [comment]
> So what should we do ?
> 
> I think it can be an addon since almost nobody use crypto it’s pretty rare

many people requested it xD
once tested i would implement it in the main project but for now, its fine as addon

**Comment by MrWeez** [comment]
> So what should we do ?
> 
> I think it can be an addon since almost nobody use crypto it’s pretty rare

I'll try to test it. I just had a few dollars in usdt and ton

**Comment by S0ly** [comment]
Ho okay 🤔

**Comment by 1day2die** [comment]
bitpave is dead anyway loll

![grafik](https://github.com/Ctrlpanel-gg/panel/assets/8725848/18ef70b4-e54c-4533-bfbb-428c574c552d)

**Comment by S0ly** [comment]
Okay so what we do of this addon and issue ?

**Comment by MrWeez** [comment]
> Okay so what we do of this addon and issue ?

Close ¯\_(ツ)_/¯

**Comment by 1day2die** [comment]
trash it
