### ISSUE TITLE
[Bug]: Logging in to suspended account

### ISSUE THREAD

**Issue by Theyka** [Ctrlpanel-gg/panel#753]
### What is your request about?

Hello. First I'm not sure thats a bug it can happen because of my modifications in controlpanel.

There is how that bug works:

1. Create two accounts, and grant administrative privileges to one of them.
2. Log in to the admin account, navigate to the users page, and suspend the second account.
3. After suspending the second account, click the "Login as User" button.
4. You should be redirected to the login page and see a message indicating that the second account has been suspended.
5. Try logging in to your admin account - you should still see the "Log back in" button.

### Branch

main

### Solution idea

The issue could be fixed by removing the 'Login as User' button for suspended accounts, but admins may still want to view suspended accounts to see what actions were taken.

**Comment by GeckoBoy84** [comment]
Intended to be able to see more info about the users activity.
