### ISSUE TITLE
[Bug]: Incorrect display of referral system data

### ISSUE THREAD

**Issue by MrWeez** [Ctrlpanel-gg/panel#759]
### What is your request about?

In the "Commission" referral system mode, the data from the "Referral reward in Credits (only for sign-up-mode):" field is displayed on the main page
![image](https://user-images.githubusercontent.com/64205495/222925802-e44fa05f-6078-4839-910b-aa4702c441dc.png)
![image](https://user-images.githubusercontent.com/64205495/222925804-f262dd19-931e-4c68-b328-dd39d40d9880.png)

### Branch

main

**Comment by 1day2die** [comment]
fixed
