### ISSUE TITLE
[Bug]: Displaying multiple verification notifications

### ISSUE THREAD

**Issue by MrWeez** [Ctrlpanel-gg/panel#760]
### What is your request about?

The panel.url/profile page displays several mail verification notifications.
![image](https://user-images.githubusercontent.com/64205495/222975586-f0221102-9606-46b6-8475-8ef3ca9cebed.png)

### Branch

main

**Comment by IceToast** [comment]
- Does this happen at any page? 
- Does this happen any time you open the profile page?

**Comment by MrWeez** [comment]
> * Does this happen at any page?
> * Does this happen any time you open the profile page?

No, this happens only on the profile page, and absolutely always.

**Comment by 1day2die** [comment]
fixed by removing the global banner. You get redirected to your profile anyway if you cant perform an action because you are not verified
