### ISSUE TITLE
[Feature] Captcha in Tickets

### ISSUE THREAD

**Issue by Vicemi** [Ctrlpanel-gg/panel#772]
### Feature Description

In order to avoid bots in the future, what can be done is to put the same captcha that is used in the login, put it in the tickets so that yes or if you have to go through it to send the ticket

### Solution Idea

In order to avoid bots in the future, what can be done is to put the same captcha that is used in the login, put it in the tickets so that yes or if you have to go through it to send the ticket

**Comment by 1day2die** [comment]
done in dev branch
