### ISSUE TITLE
[Feature] Check button to enable OMM Killer on Server Creation 

### ISSUE THREAD

**Issue by ManucrackYT** [Ctrlpanel-gg/panel#788]
### Feature Description

It should be good if you enable it because some VPS with virtualization like LXC can make servers but they must enable OMM Killer to work.

### Solution Idea

Add on Products section, in "Create Product" section, a button if you want to enable it.

**Comment by GeckoBoy84** [comment]
OMM killer doesnt exist

**Comment by ManucrackYT** [comment]
[https://media.discordapp.net/attachments/954138562234822692/1095583111242330112/1681277735650.png](url)

**Comment by GeckoBoy84** [comment]
Yes, that highlights my point! It’s OOM killer

**Comment by ManucrackYT** [comment]
Ok then could you add that check box to CPGG?

**Comment by ManucrackYT** [comment]
Could you??

**Comment by 1day2die** [comment]
comming in the next update

**Comment by 1day2die** [comment]
if possible throught the Ptero API, this will come in the next update
