### ISSUE TITLE
[Bug]: Server name missing in notifications

### ISSUE THREAD

**Issue by GeckoBoy84** [Ctrlpanel-gg/panel#833]
### What is your request about?

Server name is not included in suspend notifications

### Branch

main

### Solution idea

Add the server name to suspend notifications

**Comment by 1day2die** [comment]
this is the case because once a user runs out of credits ALL servers get suspended obviously.

We have to keep this in mind thought and have to re-check the suspension logic because of the new billing cycles @IceToast

**Comment by GeckoBoy84** [comment]
Not necessarily, all servers get suspended that cannot be paid for, but if they are cheaper you might last another few billing periods. Additionally you currently #246 get an email for each service so there is no way to differentiate between them

**Comment by IceToast** [comment]
With the new billing cycle each server must get suspended individually and thus sending a individual mail and/or notification

**Comment by S0ly** [comment]
and so have this been fixed in the dev branch ?

**Comment by S0ly** [comment]
@IceToast is it fixed ?

**Comment by S0ly** [comment]
@IceToast please
