### ISSUE TITLE
[Feature]: Additional Server selection options during creation of Tickets

### ISSUE THREAD

**Issue by GeckoBoy84** [Ctrlpanel-gg/panel#847]
### What is your request about?

Currently, the panel only shows you a server selected if you have 2 or more servers. The issue is that you might have only 1 server at the moment but wanting pre sales support or something not relating to a server.

### Branch

main

### Solution idea

The select server option should be there for even just 1 server, however an option should be added for all server amounts. This could be called “No Server” or something to show staff that it isn’t relating to a current server

**Comment by AGuyNamedJens** [comment]
Personally I wouldn't be calling this a bug, as it's not something to be considered as not working, comes closer to "I would love to have an option so people can create a ticket without having a server" which would refer to an additional option request. I've also modified the name to clarify the request.

**Comment by 1day2die** [comment]
gecko labels everything as bug and priority lol

**Comment by 1day2die** [comment]
whats the bounty
