### ISSUE TITLE
[Bug]: No Invalid Credentials error

### ISSUE THREAD

**Issue by GeckoBoy84** [Ctrlpanel-gg/panel#848]
### What is your request about?

When a user enters and submits invalid credentials on the login page, it just redirects them to the login page 

### Branch

main

### Solution idea

Return a “no account matching these credentials error”

### Additional Info

Issue is on dev branch also

**Comment by 1day2die** [comment]
this is only when logging in with a username.
the error message appears when logging in with email

**Comment by 1day2die** [comment]
fixed
