### ISSUE TITLE
[Bug]: Server Plan sorting

### ISSUE THREAD

**Issue by GeckoBoy84** [Ctrlpanel-gg/panel#850]
### What is your request about?

Server plans are currently sorted alphabetically

### Branch

development

### Solution idea

Sort them by price (low-high) as on 0.9.5

**Comment by Aang581** [comment]
🌹12

**Comment by Aang581** [comment]
#977

**Comment by 1day2die** [comment]
its sorted by price in v1.0

**Comment by 1day2die** [comment]
![grafik](https://github.com/user-attachments/assets/6203ea36-61db-4033-82cd-07e6a6037a48)
