### ISSUE TITLE
[Bug]: Server Cards Burger Menu

### ISSUE THREAD

**Issue by GeckoBoy84** [Ctrlpanel-gg/panel#852]
### What is your request about?

The burger menu has returned on server cards

### Branch

development

### Solution idea

Remove that mf

**Comment by AGuyNamedJens** [comment]
Please stop making so many tickets, just shove them all into one at this point with a checklist instead of each and every minor thing being a whole different issue request

**Comment by 1day2die** [comment]
its gone
