### ISSUE TITLE
[Bug]: PHP 8.2 failing install tests

### ISSUE THREAD

**Issue by GeekCornerGH** [Ctrlpanel-gg/panel#863]
### What is your request about?

The panel reports php 8.2 as not compatible, while being greater than 8.1
Either make the message more clear than just saying 8.1 is minimum required, or just fix this
![image](https://github.com/Ctrlpanel-gg/panel/assets/45696571/2667d652-5f81-48be-90c0-83b7afb7c0dc)

### Branch

development

**Comment by 1day2die** [comment]
did you successfully install it using php 8.2.6?

**Comment by 1day2die** [comment]
it was successfully installed using php 8.2.6. We only have to adjust the message on the installer

**Comment by AGuyNamedJens** [comment]
> The panel reports php 8.2 as not compatible, while being greater than 8.1

Basically because we currently support 8.1 due to pterodactyl being the same supported version, we didn't officially support 8.2 yet as we haven't tested it.

**Comment by GeekCornerGH** [comment]
> 
> > The panel reports php 8.2 as not compatible, while being greater than 8.1
> 
> Basically because we currently support 8.1 due to pterodactyl being the same supported version, we didn't officially support 8.2 yet as we haven't tested it.

The message is kinda misleading too

**Comment by 1day2die** [comment]
fixed
