### ISSUE TITLE
[Bug]: Error when deleting a canceled server

### ISSUE THREAD

**Issue by MrWeez** [Ctrlpanel-gg/panel#868]
### What is your request about?

When trying to delete the Canceled server, displays this error
![image](https://github.com/Ctrlpanel-gg/panel/assets/64205495/738f2b52-0ba0-44fb-aae4-8bf1752be5a6)

### Branch

development

### Controlpanel Logs

```Shell
https://pteropaste.com/jrpav004hz2j
```

**Comment by 1day2die** [comment]
hmm still gotta test it, but are you sure your ptero keys are correct

**Comment by MrWeez** [comment]
> hmm still gotta test it, but are you sure your ptero keys are correct

Yes, servers are created normally. I noticed that deleting servers does not work regardless of their state.

**Comment by 1day2die** [comment]
it takes a few seconds on my install but it does delete the server. can anyone confirm?

**Comment by MrWeez** [comment]
> it takes a few seconds on my install but it does delete the server. can anyone confirm?

I will try to completely reinstall the panel tomorrow. Although it shouldn't change anything, since I even updated the panel before sending this issue

**Comment by 1day2die** [comment]
dont make yourself the hassle. lets just have another member confirm or bust the bug^^

**Comment by MrWeez** [comment]
The problem was not confirmed, I reinstalled cpgg and everything started working
