### ISSUE TITLE
[Bug]: The referral program reward is not displayed on the home page

### ISSUE THREAD

**Issue by MrWeez** [Ctrlpanel-gg/panel#875]
### What is your request about?

Commission mode:
![image](https://github.com/Ctrlpanel-gg/panel/assets/64205495/bc94b6cb-ed70-4f8d-be29-72e13e64d670)
![image](https://github.com/Ctrlpanel-gg/panel/assets/64205495/cdee470c-8011-4919-b8d5-42eeaa13f80b)

Sign-Up mode:
![image](https://github.com/Ctrlpanel-gg/panel/assets/64205495/eff2876b-df86-4f1a-90fd-ff63215c45a4)
![image](https://github.com/Ctrlpanel-gg/panel/assets/64205495/237654da-97b6-4172-a520-f0b7bae643d4)

### Branch

development

### Controlpanel Logs

```Shell
https://pteropaste.com/szvtumhk3g3o
```

**Comment by 1day2die** [comment]
fixed
