### ISSUE TITLE
[Feature]: Displaying field names in the form of a badge

### ISSUE THREAD

**Issue by MrWeez** [Ctrlpanel-gg/panel#876]
### Feature Description

Display the role name on the role management page as a badge, not text
![image](https://github.com/Ctrlpanel-gg/panel/assets/64205495/0b483525-ec43-4857-bb87-55a6506111ce)

### Solution Idea

Replace the text with a badge, I do not know xD

**Comment by 1day2die** [comment]
im not quite sure if that would look better tbh..

**Comment by 1day2die** [comment]
![image](https://github.com/Ctrlpanel-gg/panel/assets/8725848/4fff2f79-7e58-4b40-bac6-6641f7f5fa10)

**Comment by 1day2die** [comment]
idk. have the other guys decide. i like the old version more.
