### ISSUE TITLE
[Bug]: Error when trying to sort roles

### ISSUE THREAD

**Issue by MrWeez** [Ctrlpanel-gg/panel#877]
### What is your request about?

When trying to sort a role by the number of users, or by the number of permissions, an error occurs

![image](https://github.com/Ctrlpanel-gg/panel/assets/64205495/96ffcdc4-934c-4db9-ad31-2e4c4fb284c4)

### Branch

development

### Controlpanel Logs

```Shell
https://pteropaste.com/2b4v1vp6tjn7
```

**Comment by GeckoBoy84** [comment]
Duplicate #455
