### ISSUE TITLE
[Bug]: Inability to translate the billing period type

### ISSUE THREAD

**Issue by MrWeez** [Ctrlpanel-gg/panel#884]
### What is your request about?

There is no way to translate the billing period value on the /servers/create page in the server card
![image](https://github.com/Ctrlpanel-gg/panel/assets/64205495/aa46b102-4a8a-402a-95ae-95a7e7b71aca)

### Branch

development

**Comment by 1day2die** [comment]
https://github.com/Ctrlpanel-gg/panel/pull/1025
