### ISSUE TITLE
[Bug]: Last Updated (Tickets)

### ISSUE THREAD

**Issue by GeckoBoy84** [Ctrlpanel-gg/panel#886]
### What is your request about?

The last updated column on both user and admin view does not display correctly. It either only changes when the status changes, or only on a moderator reply.

### Branch

main

### Solution idea

It should change when any new message is sent in the ticket.

### Additional Info

0.9.1

**Comment by kenshin133** [comment]
to reproduce :
create ticket, check : last updated 2 seconds ago
update as user : last updated 12 seconds ago 
update again : last updated 40 seconds ago

move to "ticket list" as a dev user

updated ticket : last updated 6 seconds ago

This is still present in 0.9.1
on 0.10.0 I cant create tickets, so Ill have to revisit.

**Comment by S0ly** [comment]
@kenshin133 can you check if this issues have been fixed whit the latest commit from 1d2d on this PR https://github.com/Ctrlpanel-gg/panel/pull/952 ?

**Comment by kenshin133** [comment]
Seems not so much. 
I pulled the panel-fix repo and this is the log output when i try to make a ticket 
https://pteropaste.com/0u5q

**Comment by kenshin133** [comment]
This is resolved by the fixes mentioned, the last updated timer updates regardless of who updates the ticket now.

**Comment by S0ly** [comment]
fixed by PR https://github.com/Ctrlpanel-gg/panel/pull/952
