### ISSUE TITLE
razorpay as a payment gateway

### ISSUE THREAD

**Issue by shawn3308** [Ctrlpanel-gg/panel#887]
### Feature Description

This is about a payment gate which is used in India 

### Solution Idea

By having this payment gateway will help many of the Indian customers who use this panel cause the payment gateway is a very popular payment gateway in India

Website: https://razorpay.com/
SandBox: https://razorpay.com/docs/api/authentication/

**Comment by S0ly** [comment]
added in the market by 1d2d, I consider it as added
