### ISSUE TITLE
[Bug]: resend verification email has no limit

### ISSUE THREAD

**Issue by OddDevelopment** [Ctrlpanel-gg/panel#888]
### What is your request about?

When you get the notification on new accounts to verify your email you can click the resend button an unlimited number of times, this could cause the email to get blocked.

### Branch

main

### Solution idea

Add a limit of 3 an hour or something, you could also do a captcha so it would be hard to automate/spam.

### Controlpanel Logs

```Shell
Not needed for this issue
```

**Comment by AGuyNamedJens** [comment]
Fixed in #952.
