### ISSUE TITLE
Infinite Credits Bug

### ISSUE THREAD

**Issue by ZribeDev** [Ctrlpanel-gg/panel#891]
### What is your request about?

When syncing and then desyncing and then doing it all again it just gives u more credits

### Branch

main

### Solution idea

Just make a variable in the db and then store if the user has already linked the discord ever

**Comment by sybetjeh** [comment]
This doesn't happen when I try it. You need to give more information like someone told you in the discord server

**Comment by ZribeDev** [comment]
Well the info is when i set the discord reward to 1 and then people can sync and unsync and then again and again and they get credits. what more do u need?

**Comment by 1day2die** [comment]
Can you reproduce the error yourself and record it by any Chance?

**Comment by ZribeDev** [comment]
Sadly no because I already Uninstaller the panel because I am migrating to
Blesta.

**Comment by 1day2die** [comment]
Not reproducable
