### ISSUE TITLE
[Feature] Allow Users to change the game they are running.

### ISSUE THREAD

**Issue by Sebuschka** [Ctrlpanel-gg/panel#893]
### Feature Description

Sometimes it would be nice, if a user could just change the nest / egg of the server.
Maybe this can be integratet just like the up / downgrade of the product itself.

### Solution Idea

Just a small drop Down menu which lets users pick the Software / Game together witch the Specification (nest).

Than on pterodactyl side, just stop the server (or even delete it) and reinstall it with another game / version.

**Comment by GeckoBoy84** [comment]
Just create a new server. The files would not be of any use so there is no reason not to.
