### ISSUE TITLE
[Bug]: double topbar entries (or install errors) 

### ISSUE THREAD

**Issue by kenshin133** [Ctrlpanel-gg/panel#898]
### What is your request about?

![image](https://github.com/Ctrlpanel-gg/panel/assets/29851415/6272a976-03c1-44de-a44a-96e9d0e4629c)
I saw this on my recent fresh install.. as far as I know the seeding step may have ran twice, but not three times. 
I removed the db, and .env file, then created a new db and ran install again in browser, 
![image](https://github.com/Ctrlpanel-gg/panel/assets/29851415/0c2b2fcb-15ac-4ffb-9ada-d2801e2cbd17)

Could be unrelated but Ill attach whole install log just in case its helpful for this issue or others. 

during install it said it failed, but I clicked to continue again and it completed. (likely seeding again and causing the double situation. 

### Branch

development

### Solution idea

During install it said it failed, but I clicked to continue again and it completed. (likely seeding again and causing the double situation. [](url)
[installer.log](https://github.com/Ctrlpanel-gg/panel/files/12208036/installer.log)
[laravel.log](https://github.com/Ctrlpanel-gg/panel/files/12208037/laravel.log)
[cron.log](https://github.com/Ctrlpanel-gg/panel/files/12208038/cron.log)

**Comment by MrWeez** [comment]
You can configure this in the useful links section

**Comment by 1day2die** [comment]
yeah the installer fails on the seeding step of the installation, but if you click "continue" again, it will succeed. i couldnt wrap my head around why this happens yet

**Comment by kenshin133** [comment]
==> laravel.log <==
[2023-08-02 00:20:03] production.DEBUG: Failed to construct Pterodactyl client, Settings table not available? {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'field list' (SQL: select `name`, `payload` from `settings` where `group` = pterodactyl) at /var/www/controlpanel/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760)

This was the first error on my new install. will attach the tail -f from all three logs starting at the pre-install checks, to when the seeding fails. 
[seedingfailed.log](https://github.com/Ctrlpanel-gg/panel/files/12234865/seedingfailed.log)

**Comment by S0ly** [comment]
have this been fixed in the dev branch ?

**Comment by kenshin133** [comment]
I do think so. And if not it was a side effect of a larger bigger problem
so it's not a priority.

**Comment by S0ly** [comment]
Okay, we are fixing the installer anyway on the next version , so would you like to close this issue ?

**Comment by kenshin133** [comment]
Yes, please!
I'll reopen if I hit it again.

**Comment by S0ly** [comment]
okay thanks !

**Comment by S0ly** [comment]
Issue may be resolved in futur version or is already resolved
