### ISSUE TITLE
[Feature]: Set limits for how many servers a user can have of a plan type

### ISSUE THREAD

**Issue by OddDevelopment** [Ctrlpanel-gg/panel#912]
### Feature Description

Add an option to products called something like "User limit", This will let admins add a limit to how many servers a user can make of each plan.

### Solution Idea

Add an option to products
When a server is made check if the user already has a server with that plan (or however many servers the admin set for the product.)

**Comment by LavishSphere** [comment]
Agreed, this would be a great idea, it would allow us to allow users for like say make 1 Node.js server, 1 python bot, 1 Minecraft server, 1 Rust, and so on and on.

**Comment by OddDevelopment** [comment]
> #849 I dont know if its a duplicate or if its similar in some ways

Looks like it, Thanks.
