### ISSUE TITLE
[Feature] Partner Products

### ISSUE THREAD

**Issue by LavishSphere** [Ctrlpanel-gg/panel#916]
### Feature Description

Create seperate products for partners. It allows us to manually assign products just for partners which could be better than giving them a discount on the store or their new users discounts on the store.

### Solution Idea

For example, if I have a partner maybe I want them to benefit from allowing their servers on a more discounted plan or a plan that costs 0 credits if you understand what I mean. I am talking about how partners for say in a Minecraft hosting or a DIscord bot hosting could benefit from cheaper plans / free plans or products on a better node.

**Comment by sybetjeh** [comment]
Can't you just set the discount to 100%? Basically achieves the same thing

**Comment by LavishSphere** [comment]
> Can't you just set the discount to 100%? Basically achieves the same thing

No. They can choose any of the plans and buy it then. I want to give them a specific plan not let them choose or buy the other plans.

**Comment by sybetjeh** [comment]
> > Can't you just set the discount to 100%? Basically achieves the same thing
> 
> No. They can choose any of the plans and buy it then. I want to give them a specific plan not let them choose or buy the other plans.

Doesn't this defeat the purpose of our partner feature? This would need a whole rewrite if I understand what you're suggesting here.

Why can't you just give them the plan yourself? Give them enough credit for the plan you want them to have and tell them to buy it?

**Comment by S0ly** [comment]
yep it would make Partner too complicated I think, give them a 100% discount and tell them to not buy some types of servers.. (Partner are special person to who you have special contract most of the time I would tell) maybe you could check the gift code too if it does not fit your needs better :D

and if you need really really special product, you could just create it directly for them in the pterodactyl panel and link their user to it it would be simpler

**Comment by S0ly** [comment]
As discussed, the proposed feature isn't feasible and not planned at this time due to the complexities it would introduce.

Thank you for your understanding and suggestion :)
