### ISSUE TITLE
[Bug]: No allocation satisfying the requirements for automatic deployment on this node were found

### ISSUE THREAD

**Issue by boomerangBS** [Ctrlpanel-gg/panel#917]
### What is your request about?

Hello, everything was working normally and suddenly, when I create a server, it gives me this error: No allocation satisfying the requirements for automatic deployment on this node were found.

Remaining allocations and resources on the node

### Branch

main

### Controlpanel Logs

```Shell
https://pteropaste.com/84qxfble16z7/
```

**Comment by MrWeez** [comment]
Create more allocations on your node in your pterodactyl panel

**Comment by boomerangBS** [comment]
I have 20 allocations free

**Comment by boomerangBS** [comment]
Help

**Comment by 1day2die** [comment]
hi please join our discord for help :)
