### ISSUE TITLE
[Feature] Don't send notifications to suspended users

### ISSUE THREAD

**Issue by LavishSphere** [Ctrlpanel-gg/panel#918]
### Feature Description

It is best not to waste e-mails on users already susepnded when notifying all users on ctrlpanel. Lol, I didn't even know it did that until I checked my verification e-mail mailbox and found a reply with a hate kys message.

### Solution Idea

Don't send notifications when notifying all users to suspended users.

**Comment by OddDevelopment** [comment]
Agreed. Also an unsubscribe link would be nice for people to opt out of emails if for example someone signed them up without there consent.

**Comment by S0ly** [comment]
this would actually be a medium priority since its required to have an unsubscribe and email management
but I think I will do a PR for all these email stuff
