### ISSUE TITLE
[Feature] Custom Message for PDF

### ISSUE THREAD

**Issue by jameskitt616** [Ctrlpanel-gg/panel#919]
### Feature Description

I'd like to see a function to print a custom message onto every invoice.
Reason behind this is, in Germany there is a law stating if you are using some special regulation for small businesses (Kleinunternehmerregelung) you do not need to ask the buyers for taxes but you *need* to state it on the Invoice.

### Solution Idea

Add a Text input field next to the Settings -> Invoices

**Comment by sybetjeh** [comment]
Ctrlpanel is general hostings, it builds the foundation needed to do that.

The beauty of Ctrlpanel is, it's open source. We can't (and probably) won't add every specific country feature needed to be legal. I recommend for features specific like this & that'll only be useful for a handful of people to create a bounty or possibly add it yourself (adding a new text field in a pdf does not require rocket science).
