### ISSUE TITLE
[Feature] An option to force a first and last name, address, phone number for signups/making a server.

### ISSUE THREAD

**Issue by OddDevelopment** [Ctrlpanel-gg/panel#923]
### Feature Description

On the signup page if something like "Require Personal Information" is ticked it will require you to enter your name, address and phone number on signup. Or you could do something like discord verification where its required before making a server.

### Solution Idea

On the signup page if something like "Require Personal Information" is ticked it will require you to enter your name, address and phone number on signup. Or you could do something like discord verification where its required before making a server.

### Additional Info

If you wanted to you could make it a toggle for each piece of information so if a host wanted they could ask for phone numbers but not address or name or something like that.

**Comment by LavishSphere** [comment]
Basically https://github.com/Ctrlpanel-gg/panel/issues/368

**Comment by OddDevelopment** [comment]
Fair enough
