### ISSUE TITLE
[Bug]: Credits/Server slots not coming to account after payment with stripe

### ISSUE THREAD

**Issue by Its-Krzysztof** [Ctrlpanel-gg/panel#924]
### What is your request about?

Hello! I configured stripe properly, but when I pay with card and after successfull payment, redirects me to the panel, but it is not giving me any credits/server slots
![image](https://github.com/Ctrlpanel-gg/panel/assets/77639981/3ea7a42f-81dc-4172-a8d0-ad42ae6bb7ae)

### Branch

main

**Comment by MrWeez** [comment]
Good afternoon. Please create a forum post on our Discord server, we do not provide support on github.
