### ISSUE TITLE
[Bug]: Verbiage on register a new membership screen

### ISSUE THREAD

**Issue by purejosh** [Ctrlpanel-gg/panel#927]
### What is your request about?

When registering a new membership and using an email that's already in use, it says the following: 
![image](https://github.com/Ctrlpanel-gg/panel/assets/70633949/0a0bb3d4-a96a-45c2-9c37-8b921e3eb74c)

### Branch

main

### Solution idea

Recommend not mentioning Pterodactyl, and also changing the second part. 
`Account already exists, please contact Support.`
Maybe include which detail is duplicate, such as username or email.

**Comment by purejosh** [comment]
Another improvement: 
![image](https://github.com/Ctrlpanel-gg/panel/assets/70633949/881f7b20-05b2-4d89-be94-73ccce0cb34d)
Recommend changing to:
```
Email verification required!
You must verify your email address before proceeding. Click here to resend verification email!
Please contact support if you do not receive your verification email.
```

**Comment by MrWeez** [comment]
Good afternoon. If you have problems with the installation, please create a forum post in the support channel on our Discord server.

**Comment by purejosh** [comment]
I never used the word `install` anywhere in my post. Not sure where you got that from.

**Comment by MrWeez** [comment]
I'm sorry, it seemed to me that you had problems registering 😅

**Comment by purejosh** [comment]
No, all good there. Just providing feedback for improving the english used in the panel.

**Comment by MrWeez** [comment]
> ### What is your request about?
> When registering a new membership and using an email that's already in use, it says the following: ![image](https://private-user-images.githubusercontent.com/70633949/302085086-0a0bb3d4-a96a-45c2-9c37-8b921e3eb74c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNzQ3ODEsIm5iZiI6MTcwNzA3NDQ4MSwicGF0aCI6Ii83MDYzMzk0OS8zMDIwODUwODYtMGEwYmIzZDQtYTk2YS00NWMyLTljMzctOGI5MjFlM2ViNzRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDE5MjEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3ZmJlYmFkYjBjNTRmZDRhZmIxZGE3NDQ1YWRmNmQ2YTFhYTdkY2NiMjkxYzczMmViMWNiYzZiMTRmMmEyMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uMsOSYlYV1kreDrmUWwDLl_9Q5hwkCRXLLmIV3TtVuw)
> 
> ### Branch
> main
> 
> ### Solution idea
> Recommend not mentioning Pterodactyl, and also changing the second part. `Account already exists, please contact Support.` Maybe include which detail is duplicate, such as username or email.
> 
> ### Controlpanel Logs
> _No response_
> 
> ### Additional Info
> _No response_

I don't think there is an error here, because when registering with the same email that already exists in Pterodactyl, an error appears in the API response. Also, if the user has an account in pterodactyl, but not in cpgg, the same text will be displayed

**Comment by purejosh** [comment]
> I don't think there is an error here, because when registering with the same email that already exists in Pterodactyl, an error appears in the API response. Also, if the user has an account in pterodactyl, but not in cpgg, the same text will be displayed

There is no bug. This github was opened to give you more clear verbiage to use for those two sections. They're worded poorly, that is all.

**Comment by 1day2die** [comment]
Thanks man. Instead of opening an issue you could also just edit the files here on github and make a pull request! :)

I will keep this in my head unless someone else decides to fix the wording

**Comment by purejosh** [comment]
Sorry, I should've thought that way too, but I assumed this would be a quick and easy feedback. Now that we're here, yeah, it would've made more sense to submit a PR. 

In my defense, I have no idea how PHP works. So I'd have to heavily rely on search to find anything. 

Are all these various texts located in the lang?

**Comment by 1day2die** [comment]
hi,

yeah, all these can be changed in the lang/en.json file.

Feel free to make an edit to those :)
