### ISSUE TITLE
[Bug]: Discord verification does not work / v0.10

### ISSUE THREAD

**Issue by MrWeez** [Ctrlpanel-gg/panel#933]
### What is your request about?

When trying to link a discord, an error occurs that the client_id field is required

### Branch

development

### Additional Info

![image](https://github.com/Ctrlpanel-gg/panel/assets/64205495/bf45c384-2a90-4340-83f6-f7f35d336d33)
![image](https://github.com/Ctrlpanel-gg/panel/assets/64205495/825f8869-a979-4fc8-8da9-a49190e3e64e)

**Comment by IceToast** [comment]
This is because of how the sociallite driver gets populated with the credentials:
![image](https://github.com/Ctrlpanel-gg/panel/assets/54889359/eb5aa40c-6adb-487b-a451-4bcb7ec63cd3)
`config/services.php`

It doesnt get filled with the settingsdata from the db

**Comment by S0ly** [comment]
<img width="167" alt="image" src="https://github.com/Ctrlpanel-gg/panel/assets/86328249/9c8b74fc-2493-45d2-b46a-bbed6b4b70d1">
xDDDD

**Comment by IceToast** [comment]
> <img alt="image" width="167" src="https://private-user-images.githubusercontent.com/86328249/333521871-9c8b74fc-2493-45d2-b46a-bbed6b4b70d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NDE3NDYsIm5iZiI6MTcxNjU0MTQ0NiwicGF0aCI6Ii84NjMyODI0OS8zMzM1MjE4NzEtOWM4Yjc0ZmMtMjQ5My00NWQyLWI0NmEtYmJlZDZiNGI3MGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDA5MDQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2ZGRmYzUwMGY2NGNlNjYxZTJiYWQ2YTIwOGExMTE4NThkYjZlNjI1ZGY3ZTFmNWZhZmJiNTVhNTA3ODY1ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8wUJ9EwOThgow-K-6IVeysSnmWlaGG_t0u1JyFc_jug"> xDDDD
> at least you know who to blame

Nah that happened before the db settings were like they are now

**Comment by S0ly** [comment]
its a joke ):

**Comment by AGuyNamedJens** [comment]
Fixed in #952
