### ISSUE TITLE
[Bug]: Ptero server description not handled correctly

### ISSUE THREAD

**Issue by S0ly** [Ctrlpanel-gg/panel#936]
### What is your request about?

wen a server on pterodactyl panel have a description too long it make the syncing process of the databases impossible and give a error 500 because the cpgg database visibly dont have the same description lengths

### Branch

main

### Solution idea

just make the same database as pterodactyl and check if other things would not get the same problems, like eggs description idk...

**Comment by AGuyNamedJens** [comment]
I wonder who needs a million characters in their description?
Anyways, We use String, while Pterodactyl uses Text for that specific field, seems to be a bit annoying (migration file has to be created for that change) to be changed..

**Comment by S0ly** [comment]
yep we are just putting the servers specs in their descriptions but here a few hundreds of character make the thing crash

**Comment by AGuyNamedJens** [comment]
Ah right, guess i'll have to add a new migration to fix that, not sure if it will delete all existing descriptions yet (it probably will, rip)

**Comment by S0ly** [comment]
Closed by PR #950
