### ISSUE TITLE
[Bug]: Better Readme and Github

### ISSUE THREAD

**Issue by S0ly** [Ctrlpanel-gg/panel#944]
### What is your request about?

Updating the Github and Readme 

### Branch

main

### Solution idea

it would be nice to have a more complete readme whit links not broken because for exemple the contribution and demo link is broken, no code of conduct, the gitignore could be clearer

just have the GitHub updated, deactivate the part not needed like actions, package it can be done easily

I can do a pull request :D

**Comment by 1day2die** [comment]
i will adress this soon, true

**Comment by S0ly** [comment]
@1day2die, I've noticed several issues:
- The .gitignore lacks documentation and clarity. There are also redundant .gitignore files that repeat the main one. It might be helpful to consolidate and provide options.
- There's no code of conduct. Adding one and moving it to .github along with contribution guidelines would be beneficial. Ensure to link them in the main README.
- Consider moving BUILDING.md to the development folder as part of pull request #945 and linking it to the main README.
