### ISSUE TITLE
[Bug]: Creating tickets not possible on 0.10.0

### ISSUE THREAD

**Issue by kenshin133** [Ctrlpanel-gg/panel#954]
### What is your request about?

two thinks: 

when I try to create a new ticket it will either reload the page (and not create anything) 
or it will tell me "429 | too many requests" This being on the second attempt to open a ticket, so its a bit aggressive and I think something is spamming in the background. 

### Branch

development

### Ctrlpanel Logs
 tail -f /var/www/controlpanel/storage/logs/*log /var/log/* /var/log/*/*log
==> /var/log/nginx/access.log <==
192.168.13.13 - - [22/May/2024:01:41:37 +0000] "POST /ticket/new HTTP/1.0" 302 422 "https://stupidsite.com/ticket/new" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
192.168.13.13 - - [22/May/2024:01:41:37 +0000] "GET /ticket/new HTTP/1.0" 200 127164 "https://stupidsite.com/ticket/new" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
192.168.13.13 - - [22/May/2024:01:41:37 +0000] "GET /_debugbar/assets/stylesheets?v=1676989262&theme=auto HTTP/1.0" 200 242640 "https://stupidsite.comticket/new" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
192.168.13.13 - - [22/May/2024:01:41:37 +0000] "GET /_debugbar/assets/javascript?v=1676989262 HTTP/1.0" 200 371661 "https://stupidsite.com/ticket/new" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
192.168.13.13 - - [22/May/2024:01:41:37 +0000] "GET /plugins/summernote/summernote-bs4.min.js.map HTTP/1.0" 200 427684 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
192.168.13.13 - - [22/May/2024:01:41:38 +0000] "GET /plugins/moment/moment.min.js.map HTTP/1.0" 200 86532 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

### Additional Info

no logs seem to be going on.. 

The tickets are NOT being created in the database.

**Comment by S0ly** [comment]
yep lots of pterodactyl error in the logs

**Comment by kenshin133** [comment]
Updated the info now that the other issue is solved. this issue persists.

**Comment by 1day2die** [comment]
we would need the laracvel logs 

tail -n 100 /var/www/controlpanel/storage/logs/laravel.log | nc pteropaste.com 99

**Comment by kenshin133** [comment]
can do, but there is no output in that log when this happens. 
 https://pteropaste.com/kfy5
 
 ### --- Logging Settings --- ###
LOG_CHANNEL=stack
LOG_LEVEL=debug

**Comment by S0ly** [comment]
does it put you a captcha error ?

**Comment by kenshin133** [comment]
Not that I know of, I don't even see a captcha.

**Comment by S0ly** [comment]
we are on dev branch 
<img width="1505" alt="image" src="https://github.com/Ctrlpanel-gg/panel/assets/86328249/747f8e0a-f34e-469c-800e-7e18b3547ff6">

and creating tickets work

**Comment by S0ly** [comment]
ethier flame fixed it in my theme or the problem is related to the installer that I have or csrf token

**Comment by kenshin133** [comment]
Ill clean up my repo and reinstall.

**Comment by kenshin133** [comment]
ctrlpanel-gg/panel:developement doesnt work for me. S0ly/panel : fix/panel-installer also no joy.

I did not configure email but dont see any errors ( a thought ).

**Comment by S0ly** [comment]
You may have some known error that are still not fixed

**Comment by S0ly** [comment]
should have been fixed in PR #952
