### ISSUE TITLE
[Bug]: Error 500 if the price is more than 999 on the checkout

### ISSUE THREAD

**Issue by MrWeez** [Ctrlpanel-gg/panel#961]
### What is your request about?

If the price of the product in the store is more than 999, an error 500 occurs. I already have a solution to this problem, and I will do a PR soon

### Branch

main

### Solution idea

I'll fix it within an hour, probably

### Ctrlpanel Logs

```Shell
[previous exception] [object] (TypeError(code: 0): NumberFormatter::formatCurrency(): Argument #1 ($amount) must be of type float, string given at /var/www/controlpanel/app/Models/ShopProduct.php:59)
[stacktrace]
```

**Comment by AGuyNamedJens** [comment]
Resolved with #963
