### ISSUE TITLE
[Bug]: no settings for tax in 0.10

### ISSUE THREAD

**Issue by S0ly** [Ctrlpanel-gg/panel#971]
### What is your request about?

there is just no settings for tax maybe could be nice to have one xD

### Branch

development

**Comment by jameskitt616** [comment]
But there is, Tax Value in the Payment settings?
![image](https://github.com/Ctrlpanel-gg/panel/assets/52933658/a689cfee-2b7e-4268-b9f4-d6ea8850095c)

**Comment by S0ly** [comment]
@jameskitt616 is that the v0.10 ?

**Comment by S0ly** [comment]
they did xD since the settings where remade they forgot

**Comment by 1day2die** [comment]
fixed, thanks lol
