### ISSUE TITLE
[Bug]: Class recapcha not found

### ISSUE THREAD

**Issue by xxcosita3czxx** [Ctrlpanel-gg/panel#975]
### What is your request about?

Cant get in settings or login page after changing site and secret key

### Branch

main

### Solution idea

I think this is just bug, but id like atleast way to disable capcha trough files

### Ctrlpanel Logs

```Shell
https://pteropaste.com/16np
```

### Additional Info

![Screenshot_2024-06-02-07-07-23-19_3aea4af51f236e4932235fdada7d1643](https://github.com/Ctrlpanel-gg/panel/assets/103898611/648661e6-1a34-4164-a9d5-b429f53a0e86)

**Comment by xxcosita3czxx** [comment]
Sorry wrong image 
![Uploading Screenshot_2024-06-18-13-43-59-59_3aea4af51f236e4932235fdada7d1643.jpg…]()

**Comment by MrWeez** [comment]
Hi! We provide support on our Discord server, could you please create a forum post in the support channel on our Discord server?

https://discord.com/invite/ctrlpanel-gg-787829714483019826

**Comment by S0ly** [comment]
yep, join the discord :)
