### ISSUE TITLE
[Feature] Checking the ability to connect to MySQL on the installer page

### ISSUE THREAD

**Issue by MrWeez** [Ctrlpanel-gg/panel#979]
### Feature Description

Now, if you enter an incorrect password, or if installer cannot connect to MySQL, you will receive an http 500 error. It seems to me that it would be a good idea to add a check for the correctness of the data specified by the user, and make an understandable error message to avoid meaningless calls to support.

### Solution Idea

Add a check for the possibility of connecting to the database, with the data that the user specified, if they are correct, continue the installation, otherwise inform the user that it is necessary to double-check the data specified by him for connection

**Comment by jameskitt616** [comment]
Did you test this with the new installer already? Cuz i think (don't remember correctly/entirely tho) i improved on that when refactoring the installer.

**Comment by MrWeez** [comment]
> Did you test this with the new installer already? Cuz i think (don't remember correctly/entirely tho) i improved on that when refactoring the installer.

Okay, I'll check it out when I get home, thanks for letting me know

**Comment by MrWeez** [comment]
> Did you test this with the new installer already? Cuz i think (don't remember correctly/entirely tho) i improved on that when refactoring the installer.

It's been almost a month, and I just checked it out. Yes, it's true, this problem has been fixed in the new installer
