### ISSUE TITLE
[Feature] Pay with PaysafeCard

### ISSUE THREAD

**Issue by FemRene** [Ctrlpanel-gg/panel#986]
### Feature Description

Maybe there should be a way to pay with PaysafeCard in the Shop. Using an Official implemented way or using a extension.

### Solution Idea

API Docs from PaysafeCard: https://www.paysafecard.com/fileadmin/api/index.html

**Comment by MrWeez** [comment]
Hi! If you need paysafecard payment gateway, you can code it yourself, or request development in the #addon-bounties channel on our discord server. You can also create a PR with the PaysafeCard payment gateway if you decide to do it yourself.

**Comment by 1day2die** [comment]
basically this can be done with the Tebex Gateway. I think they support PSC
