### ISSUE TITLE
[Feature] Change installer MYSQL Step

### ISSUE THREAD

**Issue by 1day2die** [Ctrlpanel-gg/panel#989]
### Feature Description

Currently the Textfields have values instead of placeholders. very annoying.
Also the default mysql Host should be "localhost" instead of mysql

### Solution Idea

just change the class. but it needs to be documented

**Comment by jameskitt616** [comment]
The default placeholder could be more sth like `e.g. localhost, 10.x.x.x, mysql, 192.168.x.x`
The more examples, the better people understand, same goes for the redis host btw
