### ISSUE TITLE
[Bug]: No Impressum and so on mobile

### ISSUE THREAD

**Issue by coolweddin** [Ctrlpanel-gg/panel#990]
### What is your request about?

I need Impressum and so on mobile because of German regulations,you see it on the register/login page,there pls move it to somewhere else,and add it other where else.

### Branch

main

**Comment by S0ly** [comment]
already present as ToS etc... if you need something specific to your country I advice to create or buy an add-on since cpgg need to be neutral and work for all country, so we cannot really implement something country specific,
check the already present ToS system Thanks ! :)

**Comment by MrWeez** [comment]
> already present as ToS etc... if you need something specific to your country I advice to create or buy an add-on since cpgg need to be neutral and work for all country, so we cannot really implement something country specific, check the already present ToS system Thanks ! :)

This is not an addon, but a bug. The Imprint page should be displayed even in the mobile version

**Comment by S0ly** [comment]
okay ;)

**Comment by 1day2die** [comment]
yeah weirdly it bugs out on a mobile view and the buttons arent shown. probably some css shit

**Comment by 1day2die** [comment]
![grafik](https://github.com/user-attachments/assets/cf678934-4339-4a61-b283-2c6d1ae161db)


fixed in v1
