### ISSUE TITLE
[Feature] Tebex Checkouts

### ISSUE THREAD

**Issue by iscrit** [Ctrlpanel-gg/panel#993]
### Feature Description

Why you should add Tebex Checkouts 

### Solution Idea

Not everyone in america has their SSN in hand, + Stripe and paypal need way too much information. Tebex needs a email and password to use their service. WHMCS panel has tebex checkout and it works perfectly. (But im not complaining this is a great billing panel)

### Additional Info

<3 please add it.

**Comment by S0ly** [comment]
added in the market by 1d2d, I consider it as added
