### ISSUE TITLE
[Feature] Translation additions

### ISSUE THREAD

**Issue by Futuraura** [Ctrlpanel-gg/panel#995]
### Feature Description

Currently there is only basic language support. MOTD, Buttons, Legal Pages, Useful Links are untranslatable.

### Solution Idea

I'd say that we make a feature where you can either auto translate everything using Deepl Api or translate all of it manually into all languages. It would be useful for companies that are aiming to support languages of the countries that do not know English for example a company that works in CIS (Russian) and Europe (English). 

It would be also nice when the client visits the website for the first time it would ask what language would the prefer.

**Comment by lezetho** [comment]
Isn't there something that we can contribute to?
