### ISSUE TITLE
[Feature] Easy addition of third-party payment systems other than PayPal and Stripe

### ISSUE THREAD

**Issue by Mixik4** [Ctrlpanel-gg/panel#996]
### Feature Description

I want to see a function or an opportunity through which / with which it will be possible to add other payment systems without getting into the main code. And also so that it can be done from the store, replenishment of the account with the possibility of entering a different number of coins / credits, and accordingly sending a request.

### Solution Idea

Adding an account replenishment mode with the ability to enter your own number of credits. Adding guides or functions where you can simply insert the code and specify what the request will look like.

**Comment by Mixik4** [comment]
Adding the function of third-party payment systems opens up a wider side for those who, for example, do not have access to PayPal. 
(As for me, not all of my audience has PayPal, because they live in the CIS countries)

**Comment by MrWeez** [comment]
> ### Feature Description
> I want to see a function or an opportunity through which / with which it will be possible to add other payment systems without getting into the main code. And also so that it can be done from the store, replenishment of the account with the possibility of entering a different number of coins / credits, and accordingly sending a request.
> 
> ### Solution Idea
> Adding an account replenishment mode with the ability to enter your own number of credits. Adding guides or functions where you can simply insert the code and specify what the request will look like.
> 
> ### Additional Info
> _No response_

I don't think there is a way to make adding payment gateways easier. Each payment provider has its own API, and without writing the code manually, you will not be able to create a gateway.

**Comment by Mixik4** [comment]
well, yes, but you can still try to add some popular payment systems available to CIS participants

**Comment by S0ly** [comment]
its already relatively simple to make 
do you have suggestion to simplify it ?

**Comment by MrWeez** [comment]
> well, yes, but you can still try to add some popular payment systems available to CIS participants

If you want, you can help do it. You can create a PR with a ready-made payment gateway of your payment provider

**Comment by S0ly** [comment]
and there is stripe that take a LOT of type of payment

**Comment by Mixik4** [comment]
> and there is stripe that take a LOT of type of payment

Регистрация Stripe в СНГ, проблематична, да и не все могут через него оплатить.

**Comment by Mixik4** [comment]
> and there is stripe that take a LOT of payment type

Not everyone can pay via Stripe, in addition, registration from the CIS is problematic.

**Comment by Mixik4** [comment]
> > well, yes, but you can still try to add some popular payment systems available to CIS participants
> 
> If you want, you can help do it. You can create a PR with a ready-made payment gateway of your payment provider

There is documentation, there is a payment gateway, but I have difficulties adding it.

**Comment by MrWeez** [comment]
> > > well, yes, but you can still try to add some popular payment systems available to CIS participants
> > 
> > 
> > If you want, you can help do it. You can create a PR with a ready-made payment gateway of your payment provider
> 
> There is documentation, there is a payment gateway, but I have difficulties adding it.

You can pay someone who knows PHP. It is impossible to simplify the process of creating a gateway, this is a physical limitation that we will not be able to overcome.

**Comment by Mixik4** [comment]
It's a pity, but then I'll try to figure it out myself, maybe something will work out...

> > > > well, yes, but you can still try to add some popular payment systems available to CIS participants
> > > 
> > > 
> > > If you want, you can help do it. You can create a PR with a ready-made payment gateway of your payment provider
> > 
> > 
> > There is documentation, there is a payment gateway, but I have difficulties adding it.
> 
> You can pay someone who knows PHP. It is impossible to simplify the process of creating a gateway, this is a physical limitation that we will not be able to overcome.
